
services:
  postgres:
    #image: postgres:16
    build:
      context: ./postgres-custom # Using custom Dockerfile to include pgvector
      dockerfile: Dockerfile.postgres
    container_name: academic_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: academic_helper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academic_fastapi
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: academic_helper
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/assignment
    depends_on:
      postgres:
        condition: service_healthy
      n8n:
        condition: service_started
    volumes:
      - ./data/uploads:/app/data/uploads
    ports:
      - "8001:8000"
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  n8n:
    image: n8nio/n8n:latest
    container_name: academic_n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://localhost:5678/
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data/uploads:/app/data/uploads 

  pgadmin:
    image: dpage/pgadmin4
    container_name: academic_pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: afritioalberts1216@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 0904161978 
    ports: 
      - "5500:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks: 
      - default

volumes:
  postgres_data:
  pgadmin_data:
  n8n_data:
